# Detect the OS
if [ "$(uname 2> /dev/null)" = 'Darwin' ]; then
  OS="MacOS"
elif command -v lsb_release>/dev/null; then
  if [[ `lsb_release -si` == 'Ubuntu' ]]; then
    OS="Ubuntu"
  elif [[ `lsb_release -si` == 'Debian' ]]; then
    OS="Debian"
  fi
fi

# Start tmux if it is available
if command -v tmux>/dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.dotfiles/zsh/oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom-oh-my-zsh

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="billybushey"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(colored-man-pages dotenv git-extras helm kubectl virtualenvwrapper vi-mode)

# Load OS specific plugins
if [[ $OS == 'MacOS' ]];then
  plugins+=(osx)
elif [[ $OS == 'Debian' ]]; then
  plugins+=(debian)
elif [[ $OS == 'Ubuntu' ]]; then
  plugins+=(ubuntu)
fi

# Load command helper plugins
if command -v aws>/dev/null; then
  plugins+=(aws)
fi

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# History
# This relies on Oh My Zsh
setopt histignorealldups sharehistory
if [[ $OS = 'MacOS' ]]; then
  bindkey "$terminfo[kcuu1]" history-search-backward
  bindkey "$terminfo[kcud1]" history-search-forward
fi

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

unsetopt AUTO_CD

source ~/.dotfiles/.shell/shell.sh
source ~/.dotfiles/.shell/git.sh
source ~/.dotfiles/.shell/node.sh
source ~/.dotfiles/.shell/ruby.sh
source ~/.dotfiles/.shell/java.sh
